### ISSUE TITLE
RuntimeError: NCCL Error 2: unhandled system error

### ISSUE THREAD

**Issue by RyanYip-Kat** [cuhksz-nlp/HET-MC#3]
当我在docker上运行run_sample.sh的时候，一直遇到这个RuntimeError: NCCL Error 2: unhandled system error问题，我是有8块的dgx-1的gpu的

**Comment by yuanheTian** [comment]
您好，感谢您提出问题。

我们的这个代码目前不支持分布式的多GPU并行训练。我们训练和测试模型的时候也没有用到分布式。我们已经更新了代码，您可以尝试重新运行。

**Comment by RyanYip-Kat** [comment]
好的,谢谢!

**Comment by RyanYip-Kat** [comment]
但是，我用我的数据训练，又遇到了另外一个问题，就是一直出现 UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters().
请问这个怎么解决？谢谢！

**Comment by yuanheTian** [comment]
这个问题是使用多GPU训练时会遇到的问题，使用单 GPU 是不会遇到这个问题。我们的建议是使用单GPU训练，因为我们发现，使用多GPU的速度与单GPU基本一致。如果单GPU内存不够，可以试着增大 --gradient_accumulation_steps 参数，但要确保该参数小于 batch size 并且能被 batch size 整除。

**Comment by RyanYip-Kat** [comment]
好的，谢谢！能不能提供下您这边下载好的数据集呢？谢谢！

**Comment by yuanheTian** [comment]
非常抱歉，由于版权原因，我们目前无法公开下载好的数据集，请谅解

**Comment by RyanYip-Kat** [comment]
理解理解！还请教你一个问题，就是训练好模型之后，我怎么能得到模型预测的摘要呢？谢谢！

**Comment by RyanYip-Kat** [comment]
我用的自己的数据区训练，单个GPU的时候，反而会遇到cuda 内存爆掉的情况:RuntimeError: CUDA out of memory. Tried to allocate 74.00 MiB (GPU 0; 31.72 GiB total capacity; 30.14 GiB already allocated; 31.88 MiB free; 30.62 GiB reserved in total by PyTorch)

**Comment by yuanheTian** [comment]
感谢您提出的问题和意见。

关于多 GPU 情况下的 UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). 问题，我们已经更新了代码，目前这个 warning 已经解决。

关于得到模型预测的摘要，在 models/model名字/model/ 目录下，有 test.sum.txt 文件，该文件包含了最优模型得到的摘要。

单GPU如果内存不够的话，可以增大--gradient_accumulation_steps，最大可以让它与 batch size 一致。如果这种情况下仍然遇到内存不够的问题，可以尝试多 GPU 训练（相关 warning 已解决）。

祝好！

**Comment by RyanYip-Kat** [comment]
好的，谢谢您的及时回答!我先试试！

**Comment by 1334389536** [comment]
@RyanYip-Kat 你爬好的数据集可以给我一份吗
